# YT crawl for audio feature analysis
by DM

In [1]:
%cd ..
%load_ext autoreload
%autoreload 2

/home/dongmin/userdata/dongmin/Robot-Radio-Station

In [2]:
import os
import tempfile
import sys
import subprocess
from time import sleep
import argparse
from pathlib import Path
from collections import defaultdict

import math
import random

import json
import csv

import numpy as np
import pandas as pd

from tqdm.auto import tqdm
import matplotlib.pyplot as plt
import IPython.display as ipd

from yt_dlp import YoutubeDL
import essentia.standard as es

/home/dongmin/miniconda3/envs/rrs-es/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
[   INFO   ] MusicExtractorSVM: no classifier models were configured by default

In [3]:
HOME = Path.home()
CWD = Path.cwd()

In [4]:
DATASET_DIR = HOME / 'userdata' / 'dongmin' / 'smp_dataset'
DATA_DIR = DATASET_DIR / 'data'
META_DIR = CWD / 'metadata'

## ~~Preprocess~~

### Import data

In [5]:
json_paths = DATA_DIR.glob('*.json')
json_paths = sorted(json_paths, key=lambda x: int(x.stem.split('.')[-1].split('-')[0]))
json_paths = list(json_paths)

len(json_paths), json_paths[:5]

(1000,
 [PosixPath('/home/dongmin/userdata/dongmin/smp_dataset/data/mpd.slice.0-999.json'),
  PosixPath('/home/dongmin/userdata/dongmin/smp_dataset/data/mpd.slice.1000-1999.json'),
  PosixPath('/home/dongmin/userdata/dongmin/smp_dataset/data/mpd.slice.2000-2999.json'),
  PosixPath('/home/dongmin/userdata/dongmin/smp_dataset/data/mpd.slice.3000-3999.json'),
  PosixPath('/home/dongmin/userdata/dongmin/smp_dataset/data/mpd.slice.4000-4999.json')])

In [6]:
playlists = []

for j_p in json_paths:
  with open(j_p, 'r') as f:
    chunk = json.load(f)
    playlists += chunk['playlists']

len(playlists), playlists[0]

(1000000,
 {'name': 'Throwbacks',
  'collaborative': 'false',
  'pid': 0,
  'modified_at': 1493424000,
  'num_tracks': 52,
  'num_albums': 47,
  'num_followers': 1,
  'tracks': [{'pos': 0,
    'artist_name': 'Missy Elliott',
    'track_uri': 'spotify:track:0UaMYEvWZi0ZqiDOoHU3YI',
    'artist_uri': 'spotify:artist:2wIVse2owClT7go1WT98tk',
    'track_name': 'Lose Control (feat. Ciara & Fat Man Scoop)',
    'album_uri': 'spotify:album:6vV5UrXcfyQD1wu4Qo2I9K',
    'duration_ms': 226863,
    'album_name': 'The Cookbook'},
   {'pos': 1,
    'artist_name': 'Britney Spears',
    'track_uri': 'spotify:track:6I9VzXrHxO9rA9A5euc8Ak',
    'artist_uri': 'spotify:artist:26dSoYclwsYLMAKD3tpOr4',
    'track_name': 'Toxic',
    'album_uri': 'spotify:album:0z7pVBGOD7HCIB7S8eLkLI',
    'duration_ms': 198800,
    'album_name': 'In The Zone'},
   {'pos': 2,
    'artist_name': 'Beyoncé',
    'track_uri': 'spotify:track:0WqIKmW4BTrj3eJFmnCKMv',
    'artist_uri': 'spotify:artist:6vWDO969PvNqNYHIOW5v0m',
    'track_name': 'Crazy In Love',
    'album_uri': 'spotify:album:25hVFAxTlDvXbx2X2QkUkE',
    'duration_ms': 235933,
    'album_name': 'Dangerously In Love (Alben für die Ewigkeit)'},
   {'pos': 3,
    'artist_name': 'Justin Timberlake',
    'track_uri': 'spotify:track:1AWQoqb9bSvzTjaLralEkT',
    'artist_uri': 'spotify:artist:31TPClRtHm23RisEBtV3X7',
    'track_name': 'Rock Your Body',
    'album_uri': 'spotify:album:6QPkyl04rXwTGlGlcYaRoW',
    'duration_ms': 267266,
    'album_name': 'Justified'},
   {'pos': 4,
    'artist_name': 'Shaggy',
    'track_uri': 'spotify:track:1lzr43nnXAijIGYnCT8M8H',
    'artist_uri': 'spotify:artist:5EvFsr3kj42KNv97ZEnqij',
    'track_name': "It Wasn't Me",
    'album_uri': 'spotify:album:6NmFmPX56pcLBOFMhIiKvF',
    'duration_ms': 227600,
    'album_name': 'Hot Shot'},
   {'pos': 5,
    'artist_name': 'Usher',
    'track_uri': 'spotify:track:0XUfyU2QviPAs6bxSpXYG4',
    'artist_uri': 'spotify:artist:23zg3TcAtWQy7J6upgbUnj',
    'track_name': 'Yeah!',
    'album_uri': 'spotify:album:0vO0b1AvY49CPQyVisJLj0',
    'duration_ms': 250373,
    'album_name': 'Confessions'},
   {'pos': 6,
    'artist_name': 'Usher',
    'track_uri': 'spotify:track:68vgtRHr7iZHpzGpon6Jlo',
    'artist_uri': 'spotify:artist:23zg3TcAtWQy7J6upgbUnj',
    'track_name': 'My Boo',
    'album_uri': 'spotify:album:1RM6MGv6bcl6NrAG8PGoZk',
    'duration_ms': 223440,
    'album_name': 'Confessions'},
   {'pos': 7,
    'artist_name': 'The Pussycat Dolls',
    'track_uri': 'spotify:track:3BxWKCI06eQ5Od8TY2JBeA',
    'artist_uri': 'spotify:artist:6wPhSqRtPu1UhRCDX5yaDJ',
    'track_name': 'Buttons',
    'album_uri': 'spotify:album:5x8e8UcCeOgrOzSnDGuPye',
    'duration_ms': 225560,
    'album_name': 'PCD'},
   {'pos': 8,
    'artist_name': "Destiny's Child",
    'track_uri': 'spotify:track:7H6ev70Weq6DdpZyyTmUXk',
    'artist_uri': 'spotify:artist:1Y8cdNmUJH7yBTd9yOvr5i',
    'track_name': 'Say My Name',
    'album_uri': 'spotify:album:283NWqNsCA9GwVHrJk59CG',
    'duration_ms': 271333,
    'album_name': "The Writing's On The Wall"},
   {'pos': 9,
    'artist_name': 'OutKast',
    'track_uri': 'spotify:track:2PpruBYCo4H7WOBJ7Q2EwM',
    'artist_uri': 'spotify:artist:1G9G7WwrXka3Z1r7aIDjI7',
    'track_name': 'Hey Ya! - Radio Mix / Club Mix',
    'album_uri': 'spotify:album:1UsmQ3bpJTyK6ygoOOjG1r',
    'duration_ms': 235213,
    'album_name': 'Speakerboxxx/The Love Below'},
   {'pos': 10,
    'artist_name': 'Nelly Furtado',
    'track_uri': 'spotify:track:2gam98EZKrF9XuOkU13ApN',
    'artist_uri': 'spotify:artist:2jw70GZXlAI8QzWeY2bgRc',
    'track_name': 'Promiscuous',
    'album_uri': 'spotify:album:2yboV2QBcVGEhcRlYuPpDT',
    'duration_ms': 242293,
    'album_name': 'Loose'},
   {'pos': 11,
    'artist_name': 'Jesse McCartney',
    'track_uri': 'spotify:track:4Y45aqo9QMa57rDsAJv40A',
    'artist_uri': 'spotify:artist:2Hjj68yyUPiC0HKEOigcEp',
    'track_name': 'Right Where You Want Me - Radio Edit Version',
    'album_uri': 'spotify:album:6022khQj4Fsvvse8f3A4lF',
    'duration_ms': 211693,
    'album_name': 'Right Where You Want Me'},
   {'pos': 12,
    'artist_name': 'Jesse McCartney',
    'track_uri': 'spotify:track:1HwpWwa6bnqqRhK8agG4RS',
    'artist_uri': 'spotify:artist:2Hjj68yyUPiC0HKEOigcEp',
    'track_name': 'Beautiful Soul',
    'album_uri': 'spotify:album:2gidE8vgVOkYufANjuvj3S',
    'duration_ms': 214226,
    'album_name': 'Beautiful Soul'},
   {'pos': 13,
    'artist_name': 'Jesse McCartney',
    'track_uri': 'spotify:track:20ORwCJusz4KS2PbTPVNKo',
    'artist_uri': 'spotify:artist:2Hjj68yyUPiC0HKEOigcEp',
    'track_name': "Leavin'",
    'album_uri': 'spotify:album:2tDCfKFy2YW9N0IwNSRdOJ',
    'duration_ms': 216880,
    'album_name': 'Departure - Recharged'},
   {'pos': 14,
    'artist_name': 'Cassie',
    'track_uri': 'spotify:track:7k6IzwMGpxnRghE7YosnXT',
    'artist_uri': 'spotify:artist:27FGXRNruFoOdf1vP8dqcH',
    'track_name': 'Me & U',
    'album_uri': 'spotify:album:0j1qzjaJmsF1FkcICf3hRu',
    'duration_ms': 192213,
    'album_name': 'Cassie'},
   {'pos': 15,
    'artist_name': 'Omarion',
    'track_uri': 'spotify:track:1Bv0Yl01xBDZD4OQP93fyl',
    'artist_uri': 'spotify:artist:0f5nVCcR06GX8Qikz0COtT',
    'track_name': 'Ice Box',
    'album_uri': 'spotify:album:4cVVEOXyUaWo7vlDWIkKsI',
    'duration_ms': 256426,
    'album_name': '21'},
   {'pos': 16,
    'artist_name': 'Avril Lavigne',
    'track_uri': 'spotify:track:4omisSlTk6Dsq2iQD7MA07',
    'artist_uri': 'spotify:artist:0p4nmQO2msCgU4IF37Wi3j',
    'track_name': 'Sk8er Boi',
    'album_uri': 'spotify:album:7h6XeTzy0SRXDrFJeA9gO7',
    'duration_ms': 204000,
    'album_name': 'Let Go'},
   {'pos': 17,
    'artist_name': 'Chris Brown',
    'track_uri': 'spotify:track:7xYnUQigPoIDAMPVK79NEq',
    'artist_uri': 'spotify:artist:7bXgB6jMjp9ATFy66eO08Z',
    'track_name': 'Run It!',
    'album_uri': 'spotify:album:49gaz5rhWWgqCw61M9700v',
    'duration_ms': 229866,
    'album_name': 'Chris Brown'},
   {'pos': 18,
    'artist_name': 'Beyoncé',
    'track_uri': 'spotify:track:6d8A5sAx9TfdeseDvfWNHd',
    'artist_uri': 'spotify:artist:6vWDO969PvNqNYHIOW5v0m',
    'track_name': 'Check On It - feat. Bun B and Slim Thug',
    'album_uri': 'spotify:album:3MJHoQUI828kmB6IpjejbW',
    'duration_ms': 210453,
    'album_name': "B'Day"},
   {'pos': 19,
    'artist_name': "Destiny's Child",
    'track_uri': 'spotify:track:4pmc2AxSEq6g7hPVlJCPyP',
    'artist_uri': 'spotify:artist:1Y8cdNmUJH7yBTd9yOvr5i',
    'track_name': "Jumpin', Jumpin'",
    'album_uri': 'spotify:album:283NWqNsCA9GwVHrJk59CG',
    'duration_ms': 230200,
    'album_name': "The Writing's On The Wall"},
   {'pos': 20,
    'artist_name': 'Sheryl Crow',
    'track_uri': 'spotify:track:215JYyyUnrJ98NK3KEwu6d',
    'artist_uri': 'spotify:artist:4TKTii6gnOnUXQHyuo9JaD',
    'track_name': 'Soak Up The Sun',
    'album_uri': 'spotify:album:5NYcTXrRZHxNyRKVOd0vs1',
    'duration_ms': 292306,
    'album_name': "C'Mon C'Mon"},
   {'pos': 21,
    'artist_name': 'The Black Eyed Peas',
    'track_uri': 'spotify:track:0uqPG793dkDDN7sCUJJIVC',
    'artist_uri': 'spotify:artist:1yxSLGMDHlW21z4YXirZDS',
    'track_name': 'Where Is The Love?',
    'album_uri': 'spotify:album:1bNyYpkDRovmErm4QeDrpJ',
    'duration_ms': 272533,
    'album_name': 'Elephunk'},
   {'pos': 22,
    'artist_name': 'Bowling For Soup',
    'track_uri': 'spotify:track:19Js5ypV6JKn4DMExHQbGc',
    'artist_uri': 'spotify:artist:5ND0mGcL9SKSjWIjPd0xIb',
    'track_name': "Stacy's Mom",
    'album_uri': 'spotify:album:3Q7xpHmP8k3HryE0LQdIk0',
    'duration_ms': 193042,
    'album_name': "I've Never Done Anything Like This"},
   {'pos': 23,
    'artist_name': 'The Click Five',
    'track_uri': 'spotify:track:1JURww012QnWAw0zZXi6Aa',
    'artist_uri': 'spotify:artist:01lz5VBfkMFDteSA9pKJuP',
    'track_name': 'Just The Girl',
    'album_uri': 'spotify:album:7gZilZGYr8M7UwEeYvdAKZ',
    'duration_ms': 234146,
    'album_name': 'Greetings From Imrie House'},
   {'pos': 24,
    'artist_name': 'Chris Brown',
    'track_uri': 'spotify:track:7DFnq8FYhHMCylykf6ZCxA',
    'artist_uri': 'spotify:artist:7bXgB6jMjp9ATFy66eO08Z',
    'track_name': 'Yo (Excuse Me Miss)',
    'album_uri': 'spotify:album:49gaz5rhWWgqCw61M9700v',
    'duration_ms': 229040,
    'album_name': 'Chris Brown'},
   {'pos': 25,
    'artist_name': 'Jonas Brothers',
    'track_uri': 'spotify:track:1TfAhjzRBWzYZ8IdUV3igl',
    'artist_uri': 'spotify:artist:7gOdHgIoIKoe4i9Tta6qdD',
    'track_name': 'Year 3000',
    'album_uri': 'spotify:album:20RAjvZ9LX2FDuDU8RDuIl',
    'duration_ms': 201960,
    'album_name': 'Jonas Brothers'},
   {'pos': 26,
    'artist_name': 'Lil Mama',
    'track_uri': 'spotify:track:1Y4ZdPOOgCUhBcKZOrUFiS',
    'artist_uri': 'spotify:artist:5qK5bOC6wLtuLhG5KvU17c',
    'track_name': 'Lip Gloss',
    'album_uri': 'spotify:album:3vgVsm9GY3i39fZ7b1sqV5',
    'duration_ms': 219773,
    'album_name': 'Lip Gloss'},
   {'pos': 27,
    'artist_name': 'Cascada',
    'track_uri': 'spotify:track:6MjljecHzHelUDismyKkba',
    'artist_uri': 'spotify:artist:0N0d3kjwdY2h7UVuTdJGfp',
    'track_name': 'Everytime We Touch - Radio Edit',
    'album_uri': 'spotify:album:5DvuKZTzEKjm0oUuhP237C',
    'duration_ms': 199120,
    'album_name': 'Everytime We Touch'},
   {'pos': 28,
    'artist_name': 'Jason Derulo',
    'track_uri': 'spotify:track:67T6l4q3zVjC5nZZPXByU8',
    'artist_uri': 'spotify:artist:07YZf4WDAMNwqr4jfgOZ8y',
    'track_name': 'Whatcha Say',
    'album_uri': 'spotify:album:0aVJmVAeEx78nAA1rAKYf7',
    'duration_ms': 221253,
    'album_name': 'Jason Derulo'},
   {'pos': 29,
    'artist_name': 'Ne-Yo',
    'track_uri': 'spotify:track:34ceTg8ChN5HjrqiIYCn9Q',
    'artist_uri': 'spotify:artist:21E3waRsmPlU7jZsS13rcj',
    'track_name': 'Miss Independent',
    'album_uri': 'spotify:album:6dTn9vJSxVTIGm4Cu5dH4x',
    'duration_ms': 232000,
    'album_name': 'Year Of The Gentleman'},
   {'pos': 30,
    'artist_name': 'Miley Cyrus',
    'track_uri': 'spotify:track:5Q0Nhxo0l2bP3pNjpGJwV1',
    'artist_uri': 'spotify:artist:5YGY8feqx7naU7z4HrwZM6',
    'track_name': 'Party In The U.S.A.',
    'album_uri': 'spotify:album:64aKkqxc3Ur2LYIKeS5osS',
    'duration_ms': 202066,
    'album_name': 'The Time Of Our Lives'},
   {'pos': 31,
    'artist_name': 'Boys Like Girls',
    'track_uri': 'spotify:track:6GIrIt2M39wEGwjCQjGChX',
    'artist_uri': 'spotify:artist:0vWCyXMrrvMlCcepuOJaGI',
    'track_name': 'The Great Escape',
    'album_uri': 'spotify:album:4WqgusSAgXkrjbXzqdBY68',
    'duration_ms': 206520,
    'album_name': 'Boys Like Girls'},
   {'pos': 32,
    'artist_name': 'Iyaz',
    'track_uri': 'spotify:track:4E5P1XyAFtrjpiIxkydly4',
    'artist_uri': 'spotify:artist:5tKXB9uuebKE34yowVaU3C',
    'track_name': 'Replay',
    'album_uri': 'spotify:album:44hyrGuZKAvITbmrlhryf8',
    'duration_ms': 182306,
    'album_name': 'Replay'},
   {'pos': 33,
    'artist_name': 'Chris Brown',
    'track_uri': 'spotify:track:3H1LCvO3fVsK2HPguhbml0',
    'artist_uri': 'spotify:artist:7bXgB6jMjp9ATFy66eO08Z',
    'track_name': 'Forever',
    'album_uri': 'spotify:album:1UtE4zAlSE2TlKmTFgrTg5',
    'duration_ms': 277106,
    'album_name': 'Exclusive - The Forever Edition'},
   {'pos': 34,
    'artist_name': 'Kesha',
    'track_uri': 'spotify:track:3uoQULcUWfnt6nc6J7Vgai',
    'artist_uri': 'spotify:artist:6LqNN22kT3074XbTVUrhzX',
    'track_name': 'Your Love Is My Drug',
    'album_uri': 'spotify:album:5peRwC6pQh8eaoIPtvmmOB',
    'duration_ms': 187133,
    'album_name': 'Animal'},
   {'pos': 35,
    'artist_name': 'Ne-Yo',
    'track_uri': 'spotify:track:2nbClS09zsIAqNkshg6jnp',
    'artist_uri': 'spotify:artist:21E3waRsmPlU7jZsS13rcj',
    'track_name': 'Closer',
    'album_uri': 'spotify:album:1nv3KEXZPmcwOXMoLTs1vn',
    'duration_ms': 234360,
    'album_name': 'Year Of The Gentleman'},
   {'pos': 36,
    'artist_name': 'Justin Bieber',
    'track_uri': 'spotify:track:69ghzc538EQSVon2Gm3wrr',
    'artist_uri': 'spotify:artist:1uNFoZAHBGtllmzznpCI3s',
    'track_name': 'One Less Lonely Girl',
    'album_uri': 'spotify:album:1rG5TDs3jYh6OU753I54CI',
    'duration_ms': 229106,
    'album_name': 'My World'},
   {'pos': 37,
    'artist_name': 'M.I.A.',
    'track_uri': 'spotify:track:1kusepF3AacIEtUTYrw4GV',
    'artist_uri': 'spotify:artist:0QJIPDAEDILuo8AIq3pMuU',
    'track_name': 'Paper Planes',
    'album_uri': 'spotify:album:1Lymt1abGCr3J06bbnmWca',
    'duration_ms': 203760,
    'album_name': 'Kala'},
   {'pos': 38,
    'artist_name': 'The Killers',
    'track_uri': 'spotify:track:7oK9VyNzrYvRFo7nQEYkWN',
    'artist_uri': 'spotify:artist:0C0XlULifJtAgn6ZNCW2eu',
    'track_name': 'Mr. Brightside',
    'album_uri': 'spotify:album:4undIeGmofnAYKhnDclN1w',
    'duration_ms': 222586,
    'album_name': 'Hot Fuss'},
   {'pos': 39,
    'artist_name': 'blink-182',
    'track_uri': 'spotify:track:12qZHAeOyTf93YAWvGDTat',
    'artist_uri': 'spotify:artist:6FBDaR13swtiWwGhX1WQsP',
    'track_name': 'All The Small Things',
    'album_uri': 'spotify:album:1fF8kYX49s5Ufv4XEY5sjW',
    'duration_ms': 168000,
    'album_name': 'Enema Of The State'},
   {'pos': 40,
    'artist_name': 'The Pussycat Dolls',
    'track_uri': 'spotify:track:2jFlMILIQzs7lSFudG9lbo',
    'artist_uri': 'spotify:artist:6wPhSqRtPu1UhRCDX5yaDJ',
    'track_name': 'Beep',
    'album_uri': 'spotify:album:0ylxpXE00fVxh6d60tevT8',
    'duration_ms': 229360,
    'album_name': 'PCD'},
   {'pos': 41,
    'artist_name': 'Justin Bieber',
    'track_uri': 'spotify:track:4I2GqMe7L2ccMpUbnDzYLH',
    'artist_uri': 'spotify:artist:1uNFoZAHBGtllmzznpCI3s',
    'track_name': 'Somebody To Love',
    'album_uri': 'spotify:album:6gdLfnf2vdNlMTyhJHaDLs',
    'duration_ms': 220920,
    'album_name': 'My Worlds'},
   {'pos': 42,
    'artist_name': 'The All-American Rejects',
    'track_uri': 'spotify:track:5lDriBxJd22IhOH9zTcFrV',
    'artist_uri': 'spotify:artist:3vAaWhdBR38Q02ohXqaNHT',
    'track_name': 'Dirty Little Secret',
    'album_uri': 'spotify:album:3PWEGZ6CYvXRnr0JCECsDe',
    'duration_ms': 193653,
    'album_name': 'Move Along'},
   {'pos': 43,
    'artist_name': 'Justin Bieber',
    'track_uri': 'spotify:track:2eJ8ij1T3cNUKiGdcUvKhy',
    'artist_uri': 'spotify:artist:1uNFoZAHBGtllmzznpCI3s',
    'track_name': 'Baby',
    'album_uri': 'spotify:album:6gdLfnf2vdNlMTyhJHaDLs',
    'duration_ms': 213973,
    'album_name': 'My Worlds'},
   {'pos': 44,
    'artist_name': 'Vanessa Carlton',
    'track_uri': 'spotify:track:5y69gQtK33qxb8a24ACkCy',
    'artist_uri': 'spotify:artist:5ILrArfIV0tMURcHJN8Q07',
    'track_name': 'A Thousand Miles',
    'album_uri': 'spotify:album:7D6BFTArx2ajtkKRVXIKO2',
    'duration_ms': 237493,
    'album_name': 'Be Not Nobody'},
   {'pos': 45,
    'artist_name': 'Cris Cab',
    'track_uri': 'spotify:track:1X5WGCrUMuwRFuYU1eAo2I',
    'artist_uri': 'spotify:artist:7vWBZm3sQ8yQvfV4nXxHXK',
    'track_name': 'Livin on Sunday',
    'album_uri': 'spotify:album:2kNznk4KDkYXifzOAUDoXN',
    'duration_ms': 201230,
    'album_name': 'Red Road'},
   {'pos': 46,
    'artist_name': 'Miley Cyrus',
    'track_uri': 'spotify:track:3utIAb67sOu0QHxBE88P1M',
    'artist_uri': 'spotify:artist:5YGY8feqx7naU7z4HrwZM6',
    'track_name': 'See You Again',
    'album_uri': 'spotify:album:6SkirMQoL4QhnXOM5MH5El',
    'duration_ms': 190453,
    'album_name': 'See You Again'},
   {'pos': 47,
    'artist_name': 'Jesse McCartney',
    'track_uri': 'spotify:track:3jkdQNkDTxxXtjSO4l0o1H',
    'artist_uri': 'spotify:artist:2Hjj68yyUPiC0HKEOigcEp',
    'track_name': 'How Do You Sleep? - Featuring Ludacris',
    'album_uri': 'spotify:album:2tDCfKFy2YW9N0IwNSRdOJ',
    'duration_ms': 208333,
    'album_name': 'Departure - Recharged'},
   {'pos': 48,
    'artist_name': 'Demi Lovato',
    'track_uri': 'spotify:track:5c1sfI6wIQEsSUw0xrkFdl',
    'artist_uri': 'spotify:artist:6S2OmqARrzebs0tKUEyXyp',
    'track_name': 'This Is Me',
    'album_uri': 'spotify:album:6vykWEBzBfEKYJxEFR1AQl',
    'duration_ms': 189186,
    'album_name': 'Camp Rock Original Soundtrack'},
   {'pos': 49,
    'artist_name': 'Avril Lavigne',
    'track_uri': 'spotify:track:6sqNctd7MlJoKDOxPVCAvU',
    'artist_uri': 'spotify:artist:0p4nmQO2msCgU4IF37Wi3j',
    'track_name': 'My Happy Ending',
    'album_uri': 'spotify:album:7851Vsjv3apS52sXUik6iF',
    'duration_ms': 242413,
    'album_name': 'Under My Skin'},
   {'pos': 50,
    'artist_name': 'We The Kings',
    'track_uri': 'spotify:track:1b7vg5T9YKR3NNqXfBYRF7',
    'artist_uri': 'spotify:artist:3ao3jf5d70Tf4fPh2bnXVl',
    'track_name': 'Check Yes Juliet',
    'album_uri': 'spotify:album:2F1hfUOuMnOxtSfrktL8VX',
    'duration_ms': 220133,
    'album_name': 'We The Kings'},
   {'pos': 51,
    'artist_name': 'Boys Like Girls',
    'track_uri': 'spotify:track:6GIrIt2M39wEGwjCQjGChX',
    'artist_uri': 'spotify:artist:0vWCyXMrrvMlCcepuOJaGI',
    'track_name': 'The Great Escape',
    'album_uri': 'spotify:album:4WqgusSAgXkrjbXzqdBY68',
    'duration_ms': 206520,
    'album_name': 'Boys Like Girls'}],
  'num_edits': 6,
  'duration_ms': 11532414,
  'num_artists': 37})

### extract uniqe track infos

In [13]:
uniq_tracks = set() # set of tuples: [ (artist, album, track) ]
durations = defaultdict(set) # dict of { track_tuple: [duration] }

for p in playlists:
  # list of tuples: [ (artist, album, track, duration) ]
  for t in p['tracks']:
    track_tuple = (t['artist_name'].strip(), t['album_name'].strip(), t['track_name'].strip())
    if track_tuple not in durations:
      uniq_tracks.add(track_tuple)
    durations[track_tuple].add(t['duration_ms'])

len(uniq_tracks), list(uniq_tracks)[:5], durations[list(uniq_tracks)[0]]

(2256502,
 [('Paschalis & Olympians', 'Oi Chryses Epitychies', 'Paradosou Loipon'),
  ('NYCYPCD', 'Splendid Church Life!', 'God Has Called Us For His Purpose'),
  ('Royce Campbell', 'Cocktail Hour', 'Romance Bossa'),
  ('Olga Tanon', 'Siente El Amor', 'Entre La Noche Y El Dia - Remix'),
  ('Gavin Bryars', 'Hommages', 'My First Homage')],
 {213306})

In [15]:
# filter classic tracks
classical = set()

for artist, album, track in list(uniq_tracks):
  album_l = album.lower()
  track_l = track.lower()
  
  if ('op. ' in track_l and 'no. ' in track_l and ('minor' in track_l or 'major' in track_l)):
    classical.add((artist, album, track))
    
  if ('op. ' in album_l and 'no. ' in album_l and ('minor' in album_l or 'major' in album_l)):
    classical.add((artist, album, track))

len(classical), list(classical)[:5]

(9301,
 [('Pyotr Ilyich Tchaikovsky',
   'Tchaikovsky: Piano Concerto No.1 : Piano Concerto No.2',
   'Piano Concerto No. 2 in G Major, Op. 44: I. Allegro brilliante e molto vivace'),
  ('Antonín Dvořák',
   'Dvorak: Symphonies Nos 7,8 & 9',
   "Dvorak: Symphony No. 9 in E Minor, Op. 95, 'From the New World': I. Adagio - Allegro molto"),
  ('Sergei Prokofiev',
   'Jascha Heifetz Violin Concertos - Original Album Classics',
   'Violin Concerto No. 2 in G Minor, Op. 63: III. Allegro ben marcato'),
  ('Frédéric Chopin',
   'Chopin: 57 Mazurkas, Vol. 1',
   'Mazurka in D major, Op. 33. No. 2'),
  ('Ludwig van Beethoven',
   'Beethoven: Complete Symphonies, Vol. 2 (Nos. 5-8)',
   'Symphony No. 5 in C Minor, Op. 67: IV. Allegro')])

In [17]:
len(uniq_tracks) - len(classical)

2247201

In [18]:
uniq_tracks = uniq_tracks - classical
len(uniq_tracks), len(uniq_tracks) == 2_247_201

(2247201, True)

In [19]:
for t in classical:
  durations.pop(t, None)

len(durations.keys())

2247201

In [21]:
durations_mean = { k: np.mean(list(v)) if len(v) > 1 else list(v)[0] for k, v in durations.items() }
durations_std = { k: np.std(list(v)) if len(v) > 1 else 0 for k, v in durations.items() }

### save infos as .csv files

In [ ]:
with open('./data/classical_tracks.csv', 'w') as f:
  writer = csv.writer(f)
  writer.writerow(['artist', 'album', 'track'])
  writer.writerows(classical)

In [22]:
with open('./data/uniq_tracks.csv', 'w') as f:
  writer = csv.writer(f)
  writer.writerow(['artist', 'album', 'track', 'druation_mean', 'duration_std'])
  
  for track in uniq_tracks:
    writer.writerow(list(track) + [durations_mean[track], durations_std[track]])

## YT metadata crawl

### Load Data

In [3]:
df = pd.read_csv('./data/uniq_tracks.csv')
df.head()

,artist,album,track,druation_mean,duration_std
0,Leslie Odom Jr.,Simply Christmas,The Christmas Song,245841.0,0.0
1,Gary Numan,Hope Bleeds,Absolution,299613.0,0.0
2,Lazerhawk,Redline,Dream Machine,207222.0,0.0
3,Benton Blount,Stripped,Wings of Your Love,241875.0,0.0
4,Morrissey,Bona Drag,Lifeguard On Duty,173440.0,0.0

In [4]:
df[df['artist'] == 'Wylie & The Wild West']

,artist,album,track,druation_mean,duration_std
36508,Wylie & The Wild West,Get Wild,Room to Roam,215533.0,0.0
57867,Wylie & The Wild West,Get Wild,I'm Gonna Be a Cowboy,135733.0,0.0
97493,Wylie & The Wild West,Glory Trail,The Grand Roundup,216466.0,0.0
207908,Wylie & The Wild West,Sky Tones,The Yodeling Fool,212253.0,0.0
340522,Wylie & The Wild West,Raven On the Wind,Raven On the Wind,237093.0,0.0
1671644,Wylie & The Wild West,Cattle Call,Cattle Call,244400.0,0.0
2009441,Wylie & The Wild West,Cattle Call,Don't Fence Me In,158866.0,0.0
2157868,Wylie & The Wild West,Rocketbuster,Montana Love Song,165946.0,0.0

### Youtube search

In [ ]:
# def search_youtube(query, max_results=5, format_output=None, download=False, cookie_path=None):
#   cmd = ["yt-dlp"]
  
#   if not download:
#     cmd.append("--skip-download")
  
#   match format_output:
#     case "url":
#       cmd.extend(["--quiet", "--get-id"])
#     case "basic":
#       cmd.extend(["--quiet", "--get-title", "--get-id"])
#     case "detailed":
#       cmd.extend(["--quiet", "--get-title", "--get-id", "--get-duration", "--get-description"])
#     case "json":
#       cmd.extend(["--quiet", "--dump-json"])
  
#   if cookie_path:
#     cmd.extend(["--cookies", cookie_path])
  
#   search_term = f"ytsearch{max_results}:{query}"
#   cmd.append(search_term)
  
#   try:
#     result = subprocess.run(cmd, capture_output=True, text=True, check=True)
    
#     if format_output == "json":
#       data = [ json.loads(line) for line in result.stdout.strip().split('\n') if line ]
#       return data
#     else:
#       return result.stdout
  
#   except subprocess.CalledProcessError as e:
#     print(f"Error: {e}", file=sys.stderr)
#     print(f"Error output: {e.stderr}", file=sys.stderr)
#     return None
#   except Exception as e:
#     print(f"Unexpected error: {e}", file=sys.stderr)
#     return None

In [7]:
test_tracks = df.head(5)
test_tracks

,artist,album,track,druation_mean,duration_std
0,Leslie Odom Jr.,Simply Christmas,The Christmas Song,245841.0,0.0
1,Gary Numan,Hope Bleeds,Absolution,299613.0,0.0
2,Lazerhawk,Redline,Dream Machine,207222.0,0.0
3,Benton Blount,Stripped,Wings of Your Love,241875.0,0.0
4,Morrissey,Bona Drag,Lifeguard On Duty,173440.0,0.0

In [8]:
def search_youtube(
  query:str, 
  max_results:int=5, 
  download:bool=False, 
  cookie_path:str=None
) -> list:
  
  ydl_opts = {
    'format': 'bestaudio/best',
    'quiet': True,
    'no_warnings': True,
    'ignoreerrors': True,
    'extract_flat': 'in_playlist',
    'default_search': f'ytsearch{max_results}',
    'cookies': cookie_path,
    'skip_download': not download,
  }
  
  # Create YoutubeDL object
  with YoutubeDL(ydl_opts) as ydl:
    results = ydl.extract_info(query, download=download)
    
    # Process results
    if 'entries' in results:
      processed_results = []
      
      for entry in results['entries']:
        if entry is None:
          continue
        
        try:
          # get more detailed infos
          video_info = ydl.extract_info(entry['url'], download=False)
          
          # extract relevant infos
          duration_seconds = video_info.get('duration', 0)
          channel_name = video_info.get('uploader', '')
          channel_id = video_info.get('channel_id', '')
          
          result = {
            'id': entry.get('id', ''),
            'title': entry.get('title', ''),
            'url': entry.get('url', ''),
            'channel_name': channel_name,
            'channel_id': channel_id,
            'duration_seconds': duration_seconds,
          }
          
          processed_results.append(result)
        
        except Exception as e:
          print(
            f"Error processing entry {entry.get('id', 'unknown')}: {e}", 
            file=sys.stderr
          )
      
      return processed_results
  
  return []

### Filter search results

In [ ]:
def filter_search_results(result:list, track_info:list, dur_tol=2) -> list:
  artist_i, _, track_i, dur_mean, dur_std = track_info
  dur_mean, dur_std = round(dur_mean / 1000), round(dur_std / 1000)
  
  filtered_results = []
  for r in result:
    artist_i, track_i = artist_i.lower(), track_i.lower()
    
    title_r, uploader_r, duration_r = r.get('title', ''), r.get('channel_name', ''), r.get('duration_seconds', None)
    title_r = title_r.lower() if title_r else ''
    uploader_r = uploader_r.lower() if uploader_r else ''
    
    if 'live' in title_r or 'cover' in title_r or 'remix' in title_r or 'instrumental' in title_r or 'karaoke' in title_r:
      continue
    
    is_right_dur = (
      dur_mean-dur_std <= duration_r <= dur_mean+dur_std
      if dur_std > 0 
      else dur_mean-dur_tol <= duration_r <= dur_mean+dur_tol
    )
    
    score = 0
    if is_right_dur:
      score += 1
    if artist_i in title_r:
      score += 1
    if track_i in title_r:
      score += 1
    if artist_i in uploader_r:
      score += 1
      
    if score > 0:
      r['score'] = score
      filtered_results.append(r)
  
  return filtered_results

### Test pipeline

In [13]:
test_tracks

,artist,album,track,druation_mean,duration_std
0,Leslie Odom Jr.,Simply Christmas,The Christmas Song,245841.0,0.0
1,Gary Numan,Hope Bleeds,Absolution,299613.0,0.0
2,Lazerhawk,Redline,Dream Machine,207222.0,0.0
3,Benton Blount,Stripped,Wings of Your Love,241875.0,0.0
4,Morrissey,Bona Drag,Lifeguard On Duty,173440.0,0.0

In [29]:
total_results = []
length = len(test_tracks)

pbar = tqdm(test_tracks.iterrows(), total=length, dynamic_ncols=True)

for i, (artist, album, track, duration_mean, duration_std) in pbar:
  # query = f'{artist.lower()} {album.lower()} {track.lower()} official lyrics'
  query = f'{artist.lower()} {track.lower()} official lyrics'
  result = search_youtube(
    query, 
    max_results=2, 
    cookie_path='./youtube_cookies.txt',
    download=False
  )
  
  if len(result) > 0:
    pbar.set_description(f"{len(result)} for {artist} - {track}")
    result = filter_search_results(result, (artist, album, track, duration_mean, duration_std))
    result = max(result, key=lambda x: x['score'])
    total_results.append(
      (artist, album, track, duration_mean, duration_std, result)
    )
  
  sleep(0.1)

  0%|          | 0/5 [00:00<?, ?it/s]

2 for Morrissey - Lifeguard On Duty: 100%|██████████| 5/5 [00:23<00:00,  4.73s/it]

In [17]:
total_results

[('Leslie Odom Jr.',
  'Simply Christmas',
  'The Christmas Song',
  245841.0,
  0.0,
  {'id': 'CUkwsdBzx48',
   'title': 'Leslie Odom Jr. - The Christmas Song (Audio Only)',
   'url': 'https://www.youtube.com/watch?v=CUkwsdBzx48',
   'channel_name': 'Leslie Odom Jr.',
   'channel_id': 'UCIiBME0nYQCeoxi7TbYlCbA',
   'duration_seconds': 246,
   'score': 4}),
 ('Gary Numan',
  'Hope Bleeds',
  'Absolution',
  299613.0,
  0.0,
  {'id': 'ttpmY1Tp0Bo',
   'title': 'Gary Numan - Absolution',
   'url': 'https://www.youtube.com/watch?v=ttpmY1Tp0Bo',
   'channel_name': 'aesthesis',
   'channel_id': 'UCTIcVgUqMPJFrM8aBRvlICA',
   'duration_seconds': 300,
   'score': 3}),
 ('Lazerhawk',
  'Redline',
  'Dream Machine',
  207222.0,
  0.0,
  {'id': 'Qw4SyZNG-0o',
   'title': 'Dream Machine',
   'url': 'https://www.youtube.com/watch?v=Qw4SyZNG-0o',
   'channel_name': 'Lazerhawk - Topic',
   'channel_id': 'UCnIj-rNV30TA1ZLpEcjCFJg',
   'duration_seconds': 207,
   'score': 3}),
 ('Benton Blount',
  'Stripped',
  'Wings of Your Love',
  241875.0,
  0.0,
  {'id': '7USyDsyJyZM',
   'title': 'Wings of Your Love',
   'url': 'https://www.youtube.com/watch?v=7USyDsyJyZM',
   'channel_name': 'Benton Blount',
   'channel_id': 'UCMuCoRcdo4Gn0DS2An7QqEg',
   'duration_seconds': 242,
   'score': 3}),
 ('Morrissey',
  'Bona Drag',
  'Lifeguard On Duty',
  173440.0,
  0.0,
  {'id': 'QxyMh42hOMU',
   'title': 'Lifeguard on Duty',
   'url': 'https://www.youtube.com/watch?v=QxyMh42hOMU',
   'channel_name': 'Morrissey - Topic',
   'channel_id': 'UC_Lm9hIkUlRr4pURZg5nE3g',
   'duration_seconds': 173,
   'score': 3})]